name: release-electron

on:
  push:
    tags:
      - v*

jobs:
  Release:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Setup WineHQ
        run: |
          sudo dpkg --add-architecture i386 &&
          sudo mkdir -pm755 /etc/apt/keyrings &&
          sudo wget -O /etc/apt/keyrings/winehq-archive.key https://dl.winehq.org/wine-builds/winehq.key &&
          sudo wget -NP /etc/apt/sources.list.d/ https://dl.winehq.org/wine-builds/ubuntu/dists/jammy/winehq-jammy.sources &&
          sudo apt update && sudo apt install --install-recommends winehq-stable

      - name: Install ElectronNET.CLI
        run: dotnet tool install ElectronNET.CLI -g
      - name: Build apps
        run: |
          electronize build /target win /p:ProductVersion=${GITHUB_REF_NAME#v} /electron-params "-p=never"
          electronize build /target linux /p:ProductVersion=${GITHUB_REF_NAME#v} /electron-params "-p=never"
