name: release-electron

on:
  workflow_dispatch:

jobs:
  Release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install ElectronNET.CLI
        run: dotnet tool install ElectronNET.CLI -g

      - name: Read json file
        id: read_json
        run: |
          ls
          content=`cat ./${{ github.event.repository.name }}/electron.manifest.json}`
          # the following lines are only required for multi line json
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          # end of optional handling for multi line json
          echo "::set-output name=packageJson::$content"
      - name: Set environment variables
        run: |
          echo "$REPO_NAME=${{ github.event.repository.name }}" >> $GITHUB_ENV
          echo "$BUILD_VERSION=${{ fromJson(steps.set_var.outputs.packageJson).build.buildVersion }}" >> $GITHUB_ENV
        
      - name: Build win target
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          electronize build /target win /electron-params "-p=never"
          if (-not [System.IO.File]::Exists("./bin/Desktop/${Env:REPO_NAME} Setup ${Env:BUILD_VERSION}.exe")) {
            echo "::error::The win target assets were not created."
          }
      - name: Build mac target
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          electronize build /target osx /electron-params "-p=never"
          if [ ! -f ./bin/Desktop/${REPO_NAME}-${BUILD_VERSION}.dmg ]; then
            echo "::error::The mac target assets were not created."
          fi
      - name: Build linux target
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          electronize build /target linux /electron-params "-p=never"
          if [ ! -f ./bin/Desktop/${REPO_NAME}-${BUILD_VERSION}.appimage ]; then
            echo "::error::The linux target assets were not created."
          fi
