name: release-electron

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  Release:
    runs-on: ubuntu-22.04
    steps:
      - name: Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Verify upload url
        run: echo ${{ github.event.client_payload }}

      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Setup WineHQ
        run: |
          sudo dpkg --add-architecture i386 &&
          sudo mkdir -pm755 /etc/apt/keyrings &&
          sudo wget -O /etc/apt/keyrings/winehq-archive.key https://dl.winehq.org/wine-builds/winehq.key &&
          sudo wget -NP /etc/apt/sources.list.d/ https://dl.winehq.org/wine-builds/ubuntu/dists/jammy/winehq-jammy.sources &&
          sudo apt update && sudo apt install --install-recommends winehq-stable

      - name: Restore dependencies
        run: dotnet restore

      - name: Build apps
        run: |
          electronize build /target win
          electronize build /target linux

      - name: Upload assets to release
        uses: csexton/release-asset-action@v3
        with:
          pattern: |
            "bin/Desktop/*.exe"
            "bin/Desktop/*.appimage"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          release-url: ${{ github.event.client_payload.url }}
        
