name: release-electron
permissions: write-all

on:
  pull_request:
    branches: 
      - main
    types:
      - closed
  workflow_dispatch:

jobs:
  Release:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Setup WineHQ
        run: |
          sudo dpkg --add-architecture i386 &&
          sudo mkdir -pm755 /etc/apt/keyrings &&
          sudo wget -O /etc/apt/keyrings/winehq-archive.key https://dl.winehq.org/wine-builds/winehq.key &&
          sudo wget -NP /etc/apt/sources.list.d/ https://dl.winehq.org/wine-builds/ubuntu/dists/jammy/winehq-jammy.sources &&
          sudo apt update && sudo apt install --install-recommends winehq-stable
          
      - name: Install ElectronNET.CLI
        run: dotnet tool install ElectronNET.CLI -g
      - name: Build apps
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          electronize build /target win /electron-params "--publish=always"
          electronize build /target linux /electron-params "--prune=true --publish=always"
